global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'report-service'
    static_configs:
      - targets: ['report-service:4000']
  
  - job_name: 'cockroachdb'
    static_configs:
      - targets: ['db:8080']
    metrics_path: '/_status/vars'
  
  - job_name: 'nats'
    static_configs:
      - targets: ['mb:8222']
    metrics_path: '/varz'
  
  - job_name: 'identity-service'
    static_configs:
      - targets: ['identity-service:3001']
  
  - job_name: 'anonymizer-service'
    static_configs:
      - targets: ['anonymizer-service:3002']