 global:
    scrape_interval: 15s
  
  scrape_configs:
    - job_name: 'report-service'
      static_configs:
        - targets: ['report-service:4000']
    
    - job_name: 'cockroachdb'
      static_configs:
        - targets: ['db:8080']
    
    - job_name: 'nats'
      static_configs:
        - targets: ['mb:8222']